json =
{u'input':
    {u'app_rate': {
        u'app_rate_Spray(all starting formulations)': u'4',
        u'app_rate_L/SC/EC': u'4'
    },
        u'expDurationType_st': True,
        u'dermal_NC_POD_source_st': u'Oral',
        u'inhalation_abs_source_it': u'Human study',
        u'inhalation_NC_POD_HEC83_lt': u'',
        u'dermal_NC_LOC_lt': u'100',
        u'inhalation_abs_source_st': u'Human study',
        u'inhalation_NC_POD_source_it': u'Oral',
        u'bw_inhalation_NC_it': u'80',
        u'dermal_abs_source_lt': u'Human study',
        u'bw_dermal_NC_it': u'80',
        u'inhalation_abs_frac_it': u'100',
        u'expDurationType_lt': False,
        u'inhalation_NC_POD_HEC83_st': u'',
        u'expDurationType_it': False,
        u'exp_scenario': {
            u'Formulation': [u'Spray(all starting formulations)', u'L/SC/EC'],
            u'AppEquip': [u'Aerial', u'Groundboom', u'Chemigation'],
            u'AppType': [u'Broadcast'],
            u'Activity': [u'Applicator', u'Flagger', u'M/L']
        },
        u'inhalation_NC_POD_lt': u'25',
        u'dermal_NC_endpoint_it': u'No',
        u'dermal_NC_POD_st': u'50',
        u'dermal_abs_frac_it': u'25',
        u'dermal_NC_POD_lt': u'50',
        u'dermal_NC_LOC_it': u'100',
        u'inhalation_NC_POD_st': u'25',
        u'activeIngredient': u'',
        u'bw_dermal_NC_st': u'80',
        u'inhalation_NC_POD_HEC29_lt': u'',
        u'inhalation_NC_POD_HEC167_st': u'',
        u'bw_inhalation_NC_lt': u'80',
        u'exp_crop': u'Alfalfa',
        u'dermal_NC_endpoint_st': u'No',
        u'inhalation_NC_POD_source_lt': u'Oral',
        u'dermal_abs_source_st': u'Human study',
        u'inhalation_NC_POD_HEC83_it': u'',
        u'inhalation_abs_source_lt': u'Human study',
        u'bw_inhalation_NC_st': u'80',
        u'inhalation_NC_POD_HEC167_it': u'',
        u'dermal_NC_POD_source_lt': u'Oral',
        u'bw_dermal_NC_lt': u'80',
        u'dermal_NC_endpoint_lt': u'No',
        u'expComboType': u'1',
        u'inhalation_NC_POD_source_st': u'Oral',
        u'dermal_abs_source_it': u'Human study',
        u'inhalation_NC_LOC_st': u'100',
        u'inhalation_NC_POD_HEC167_lt': u'',
        u'inhalation_NC_POD_HEC29_st': u'',
        u'exp_category': u'Field crop, high-acreage',
        u'inhalation_abs_frac_lt': u'100',
        u'dermal_NC_POD_source_it': u'Oral',
        u'dermal_abs_frac_st': u'25',
        u'dermal_NC_POD_it': u'50',
        u'dermal_NC_LOC_st': u'100',
        u'inhalation_NC_POD_HEC29_it': u'',
        u'dermal_abs_frac_lt': u'25',
        u'inhalation_NC_POD_it': u'25',
        u'inhalation_NC_LOC_it': u'100',
        u'inhalation_abs_frac_st': u'100',
        u'inhalation_NC_LOC_lt': u'100'
    },
// html
was
here //
u'output': {
    u'1': {
        u'active_ingredient': u'',
        u'app_rate': u'4',
        u'dermal_exp': [u'7.7', u'30.3', u'45.3'],
        u'dermal_unit_exp': [u'220.0 [SL_NO_G]', u'37.6 [SL_G]', u'29.1 [DL_G]'],
        u'formulation': u'L/SC/EC',
        u'inhal_moe': [u'1902.58751903'],
        u'inhal_dose': [u'0.01314'],
        u'loc_inhal': 100,
        u'area_treated_unit': u'acres',
        u'app_type': u'Broadcast',
        u'unit_exp_sl_no_G': u'220',
        u'dermal_moe': [u'15.1515151515', u'88.6524822695', u'114.547537228'],
        u'dermal_dose': [u'3.3', u'0.564', u'0.4365'],
        u'crop_name': u'Alfalfa',
        u'nc_POD': u'50',
        u'combined': False,
        u'inhal_unit_exp': [u'0.219 [NO_R]'],
        u'app_equip': u'Aerial',
        u'unit_exp_dl_G': u'29.1',
        u'area_treated': u'1200',
        u'bw_adult': u'80',
        u'unit_exp_sl_G': u'37.6',
        u'unit_exp_ec': u'8.6',
        u'app_rate_unit': u'lb ai/acre',
        u'abs_frac': 0.25,
        u'crop_target': u'Field crop, high-acreage',
        u'loc_dermal': 100,
        u'activity': u'M/L'
    },
    u'3': {
        u'active_ingredient': u'',
        u'app_rate': u'4',
        u'dermal_exp': [u'7.7', u'30.3', u'45.3'],
        u'dermal_unit_exp': [u'220.0 [SL_NO_G]', u'37.6 [SL_G]'],
        u'formulation': u'L/SC/EC',
        u'inhal_moe': [u'11415.5251142'],
        u'inhal_dose': [u'0.00219'],
        u'loc_inhal': 100,
        u'area_treated_unit': u'acres',
        u'app_type': u'Broadcast',
        u'unit_exp_sl_no_G': u'220',
        u'dermal_moe': [u'90.9090909091', u'531.914893617'],
        u'dermal_dose': [u'0.55', u'0.094'],
        u'crop_name': u'Alfalfa',
        u'nc_POD': u'50',
        u'combined': False,
        u'inhal_unit_exp': [u'0.219 [NO_R]'],
        u'app_equip': u'Groundboom',
        u'unit_exp_dl_G': u'29.1',
        u'area_treated': u'200',
        u'bw_adult': u'80',
        u'unit_exp_sl_G': u'37.6',
        u'unit_exp_ec': u'8.6',
        u'app_rate_unit': u'lb ai/acre',
        u'abs_frac': 0.25,
        u'crop_target': u'Field crop, high-acreage',
        u'loc_dermal': 100,
        u'activity': u'M/L'
    },
    u'2': {
        u'active_ingredient': u'',
        u'app_rate': u'4',
        u'dermal_exp': [u'7.7', u'30.3', u'45.3'],
        u'dermal_unit_exp': [u'220.0 [SL_NO_G]', u'37.6 [SL_G]'],
        u'formulation': u'L/SC/EC',
        u'inhal_moe': [u'6523.15720809'],
        u'inhal_dose': [u'0.0038325'],
        u'loc_inhal': 100,
        u'area_treated_unit': u'acres',
        u'app_type': u'Broadcast',
        u'unit_exp_sl_no_G': u'220',
        u'dermal_moe': [u'51.9480519481', u'303.951367781'],
        u'dermal_dose': [u'0.9625', u'0.1645'],
        u'crop_name': u'Alfalfa',
        u'nc_POD': u'50',
        u'combined': False,
        u'inhal_unit_exp': [u'0.219 [NO_R]'],
        u'app_equip': u'Chemigation',
        u'unit_exp_dl_G': u'29.1',
        u'area_treated': u'350',
        u'bw_adult': u'80',
        u'unit_exp_sl_G': u'37.6',
        u'unit_exp_ec': u'8.6',
        u'app_rate_unit': u'lb ai/acre',
        u'abs_frac': 0.25,
        u'crop_target': u'Field crop, high-acreage',
        u'loc_dermal': 100,
        u'activity': u'M/L'
    },
    u'5': {
        u'active_ingredient': u'',
        u'app_rate': u'4',
        u'dermal_exp': [u'7.7', u'30.3', u'45.3'],
        u'dermal_unit_exp': [u'78.6 [SL_NO_G]'],
        u'formulation': u'Spray(all starting formulations)',
        u'inhal_moe': [u'7352.94117647'],
        u'inhal_dose': [u'0.0034'],
        u'loc_inhal': 100,
        u'area_treated_unit': u'acres',
        u'app_type': u'Broadcast',
        u'unit_exp_sl_no_G': u'78.6',
        u'dermal_moe': [u'254.452926209'],
        u'dermal_dose': [u'0.1965'],
        u'crop_name': u'Alfalfa',
        u'nc_POD': u'50',
        u'combined': False,
        u'inhal_unit_exp': [u'0.34 [NO_R]'],
        u'app_equip': u'Groundboom',
        u'unit_exp_dl_G': u'12.6',
        u'area_treated': u'200',
        u'bw_adult': u'80',
        u'unit_exp_sl_G': u'16.1',
        u'unit_exp_ec': u'5.1',
        u'app_rate_unit': u'lb ai/acre',
        u'abs_frac': 0.25,
        u'crop_target': u'Field crop, high-acreage',
        u'loc_dermal': 100,
        u'activity': u'Applicator'
    },
    u'4':
        {u'active_ingredient': u'',
         u'app_rate': u'4',
         u'dermal_exp': [u'7.7', u'30.3', u'45.3'],
         u'dermal_moe': [u'1602.56410256'],
         u'formulation': u'Spray(all starting formulations)',
         u'inhal_moe': [u'85034.0136054'],
         u'inhal_dose': [u'0.000294'],
         u'loc_inhal': 100,
         u'area_treated_unit': u'acres',
         u'app_type': u'Broadcast',
         u'dermal_dose': [u'0.0312'],
         u'crop_name': u'Alfalfa',
         u'nc_POD': u'50',
         u'combined': False,
         u'inhal_unit_exp': [u'0.0049 [EC]'],
         u'app_equip': u'Aerial',
         u'area_treated': u'1200',
         u'bw_adult': u'80',
         u'unit_exp_ec': u'2.08',
         u'app_rate_unit': u'lb ai/acre',
         u'abs_frac': 0.25,
         u'dermal_unit_exp': [u'2.08 [EC]'],
         u'crop_target': u'Field crop, high-acreage',
         u'loc_dermal': 100,
         u'activity': u'Applicator'
         },
    u'6': {
        u'active_ingredient': u'',
        u'app_rate': u'4',
        u'dermal_exp': [u'7.7', u'30.3', u'45.3'],
        u'dermal_unit_exp': [u'11.0 [SL_NO_G]'],
        u'formulation': u'Spray(all starting formulations)',
        u'inhal_moe': [u'4081.63265306'],
        u'inhal_dose': [u'0.006125'],
        u'loc_inhal': 100,
        u'area_treated_unit': u'acres',
        u'app_type': u'Broadcast',
        u'unit_exp_sl_no_G': u'11',
        u'dermal_moe': [u'1038.96103896'],
        u'dermal_dose': [u'0.048125'],
        u'crop_name': u'Alfalfa',
        u'nc_POD': u'50',
        u'combined': False,
        u'inhal_unit_exp': [u'0.35 [NO_R]'],
        u'app_equip': u'Aerial',
        u'unit_exp_dl_G': u'10.6',
        u'area_treated': u'350',
        u'bw_adult': u'80',
        u'unit_exp_sl_G': u'12',
        u'app_rate_unit': u'lb ai/acre',
        u'abs_frac': 0.25,
        u'crop_target': u'Field crop, high-acreage',
        u'loc_dermal': 100,
        u'activity': u'Flagger'
    }
}
}
